language: ruby

addons:
  postgresql: "9.4"

services:
  - postgresql

branches:
    only:
        - master

script:
  - bundle exec rspec

bundler_args: "--without development"
cache:
  - bundler

notifications:
  email: false
