language: ruby

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - rake load_csv[data.csv]

branches:
    only:
        - master

script:
  - bundle exec rspec

bundler_args: "--without development"
cache:
  - bundler

notifications:
  email: false
